### ISSUE TITLE
2016.6.20-2016.6.26

### ISSUE THREAD

**Issue by terranc** [terranc/LFCMS#1]
- [x] 动态请求加载页面/组件，尽量能支持后退事件保留上一页的状态
- [x] 提供方便设置document.title的组件属性
- [x] 页面参数如何传递？路由如何配置？
- [ ] 希望路由不用每个页面都要配置，能有一个统一的路由方案为宜
- [x] 把vux整进去
- [x] 把8080端口的配置放到git库之外，比如命令行参数，因为其他人的8080可能已被占用

**Comment by weijiewow** [comment]
> 把8080端口的配置放到git库之外，比如命令行参数，因为其他人的8080可能已被占用

8080 端口是在没有提供端口号的情况下使用的默认值，支持自定义端口启动，例如像下面这样：

```
PORT=3333 npm run dev
```

我把这加入文档。

**Comment by terranc** [comment]
貌似现在还不可以这样吧？

**Comment by terranc** [comment]
![qq 20160622010932](https://cloud.githubusercontent.com/assets/224353/16239096/fd119f26-3815-11e6-825f-8977ae4591a8.png)

**Comment by weijiewow** [comment]
`PORT=3333 npm run dev`

把端口参数放前面

**Comment by weijiewow** [comment]
> 希望路由不用每个页面都要配置，能有一个统一的路由方案为宜

这个指的是？

**Comment by terranc** [comment]
希望不用每个route都需要在route.js里面一个个去配置，能根据*.vue的文件名或者其它一些规则自动定位路由，只有一些需要特别对待的才去差异化配置。还不明白，可以语音沟通。

**Comment by weijiewow** [comment]
@terranc 

这个东西我昨晚研究了一下，vue-router 是不带这样的功能的，这种按照文件影射的路由一般出现在后端，因为浏览器代码没法读取到文件。前端实在要弄的话，只能在编译阶段弄这个东西，要基于 vue-router 设计一套灵活好用的路由规则，并编码实现，工作量不小，其他人在学习完如何使用 vue-router 后，还要学习如何使用我们设计的这套规则，况且 vue-router 的配置本身足够简单，要考虑有没有必要真的自己弄一套。

附上 vue-router 的配置

``` javascript
export default function (router) {
  router.map({
    '/index': {
      name: 'index',
      component: (resolve) => {
        require(['./pages/Index'], resolve);
      },
    },
    '/setting': {
      name: 'setting',
      component: (resolve) => {
        require(['./pages/Setting'], resolve);
      },
    },
    '/article': {
      name: 'article',
      component: (resolve) => {
        require(['./pages/Article'], resolve);
      },
    },
  });

  router.redirect({
    '/': 'index',
  });
}
```

**Comment by terranc** [comment]
@MouCai 
一时没有更好方案的话，先搁置这个问题，继续其它的。

**Comment by terranc** [comment]
路由配置方式的问题，未来再解决
