### ISSUE TITLE
2016.6.27-2016.6.30

### ISSUE THREAD

**Issue by terranc** [terranc/LFCMS#2]
因为现在每个页面是动态加载的，为了防止在移动端信号不好时导致的缓慢或者终端的情况，考虑做以下处理：
- [x] 在页面加载超过1s时在屏幕中心弹出loading遮罩层
- [x] 在页面超时后弹出警示及重试刷新按钮

Other：
- [x] head里面该放的一些meta什么的都完善好

> http://www.css88.com/archives/5480
- [ ] 支持layout & 我的想法是分为三个css：
  1. [x] Normalize.css
  2. [x] vux样式
  3. [x] 补充组件的公共样式`（将来用LFCMS做任何项目，这份样式会是统一的）`
  4. [ ] 具体项目的自定义样式`（LFCMS用来做具体项目时，项目对应的特性样式）`
- [x] 模拟微信的设置，利用vux比较完整的做出一个demo
- [ ] 仿微信文章详情页，包括文章留言，做出来，补充一些vux里没有的样式（单选、多选、下拉）

**Comment by weijiewow** [comment]
> 仿微信文章详情页，包括文章留言，做出来，补充一些vux里没有的样式（单选、多选、下拉）

[多选](https://vuxjs.gitbooks.io/vux/content/form/checklist.html)，[单选](https://vuxjs.gitbooks.io/vux/content/form/radio.html)，[下拉](https://vuxjs.gitbooks.io/vux/content/form/selector.html) vux 是有的。
