### ISSUE TITLE
tabbar的用法不正确

### ISSUE THREAD

**Issue by terranc** [terranc/LFCMS#3]
因为tabbar是absolute的，所以现在的页面有滚动条以后是错位的。

![qq 20160628234029](https://cloud.githubusercontent.com/assets/224353/16422107/c3cda7ea-3d89-11e6-90dd-479b336c6446.png)

我看了下官方weui的结构。
![qq 20160628234150](https://cloud.githubusercontent.com/assets/224353/16422154/eb56f6cc-3d89-11e6-9f28-7f89994715d6.png)

因此现在这种引入的html结构不妥，而且有些样式是放在demo css里面的，并非weui.css里。估计这一块要做得整到lfcms的项目css里去。

**Comment by weijiewow** [comment]
啊擦，还有这种事，等我午休的时候看看，昨晚家里停电艹
